import javax.swing.ImageIcon;
import java.awt.*;

public class Book extends javax.swing.JFrame {
    Data d = new Data();
    SoundEffects sfx = new SoundEffects();
    int page;
    String pageFormat;
    boolean darkmode;
    /**
     * Creates new form GUI
     */
    public Book() {
        d.renderData();
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icon.png")).getImage());
        if(d.data.get(0).equals("false")){
            darkmode = true;
        }
        else{
            darkmode = false;
        }
        modeRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JLabel();
        pageIndicator = new javax.swing.JLabel();
        topIcon = new javax.swing.JLabel();
        mode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pages = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NotiQuiz");
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backW.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 790, -1, -1));

        pageIndicator.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        pageIndicator.setForeground(new java.awt.Color(0, 0, 0));
        pageIndicator.setText("0 of 963");
        getContentPane().add(pageIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 860, -1, -1));

        topIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        getContentPane().add(topIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        mode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightmode.png"))); // NOI18N
        mode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeMouseClicked(evt);
            }
        });
        getContentPane().add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, 60));

        pages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThermodynamicsAn_Engineering_Approach_5th_Edition-Cengel_page-0001.jpg"))); // NOI18N
        jScrollPane1.setViewportView(pages);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1410, 900));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitebackground.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        Menu m = new Menu();
        m.setLocationRelativeTo(null);
        m.setResizable(false);
        m.setVisible(true);
        dispose();
        sfx.playTrack("click.wav");
    }//GEN-LAST:event_backButtonMouseClicked

    private void modeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeMouseClicked
        modeRender();
        sfx.playTrack("click.wav");
    }//GEN-LAST:event_modeMouseClicked

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        int turn = evt.getWheelRotation();
        if (turn < 0 && page > 0) {
            page--;
        } else if(turn > 0 && page < 963) {
            page++;
        }
        pageChange(pageFormat());
        pageIndicator.setText(page + " of 963");
    }//GEN-LAST:event_formMouseWheelMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(darkmode){
            darkmode = false;
        }
        else{
            darkmode = true;
        }
        modeRender();
    }//GEN-LAST:event_formMouseClicked

    private String pageFormat() {
        if (page < 10) {
            pageFormat = "000" + page;
        } else if (page < 100) {
            pageFormat = "00" + page;
        } else if (page < 1000) {
            pageFormat = "0" + page;
        }
        return pageFormat;
    }
    
    private void pageChange(String format){
        try{
            pages.setIcon(new javax.swing.ImageIcon(getClass().getResource("ThermodynamicsAn_Engineering_Approach_5th_Edition-Cengel_page-" + format + ".jpg")));
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void modeRender(){
        if(darkmode){
            darkmode = false;
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitebackground.png")));
            mode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightmode.png")));
            backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backW.png")));
            pageIndicator.setForeground(new java.awt.Color(0, 0, 0));
            getContentPane().setBackground(Color.WHITE);
            d.data.set(0 , "false");
            d.saveData();
        }
        else{
            darkmode = true;
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackbackground.png")));
            mode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/darkmode.png")));
            backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backB.png")));
            pageIndicator.setForeground(new java.awt.Color(255, 255,255));
            getContentPane().setBackground(Color.BLACK);
            d.data.set(0 , "true");
            d.saveData();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mode;
    private javax.swing.JLabel pageIndicator;
    private javax.swing.JLabel pages;
    private javax.swing.JLabel topIcon;
    // End of variables declaration//GEN-END:variables
}
